// Code generated by trunnel. DO NOT EDIT.

//go:build gofuzz
// +build gofuzz

package bytesfield

func FuzzIRecv(data []byte) int {
	_, err := ParseIRecv(data)
	if err != nil {
		return 0
	}
	return 1
}
