// Code generated by trunnel. DO NOT EDIT.

package bytesfield

import "testing"

func TestIRecvCorpus(t *testing.T) {
	cases := []struct {
		Data []byte
	}{
		{
			Data: []byte{0xc0, 0xfc, 0x2f, 0xfa, 0xc2, 0xfd, 0x94, 0x1},
		},
	}
	for _, c := range cases {
		_, err := ParseIRecv(c.Data)
		if err != nil {
			t.Fatal(err)
		}
	}
}
