// Code generated by trunnel. DO NOT EDIT.

package bytesfield

import "errors"

type IRecv struct {
	Bytes [8]uint8
}

func (i *IRecv) Parse(data []byte) ([]byte, error) {
	cur := data
	{
		if len(cur) < 8 {
			return nil, errors.New("data too short")
		}
		copy(i.Bytes[:], cur[:8])
		cur = cur[8:]
	}
	return cur, nil
}

func ParseIRecv(data []byte) (*IRecv, error) {
	i := new(IRecv)
	_, err := i.Parse(data)
	if err != nil {
		return nil, err
	}
	return i, nil
}

func (i *IRecv) encodeBinary() []byte {
	var buf []byte
	buf = append(buf, i.Bytes[:]...)
	return buf
}

func (i *IRecv) MarshalBinary() ([]byte, error) {
	if err := i.validate(); err != nil {
		return nil, err
	}
	return i.encodeBinary(), nil
}

func (i *IRecv) validate() error {
	if len(i.Bytes) != 8 {
		return errors.New("array length constraint violated")
	}
	return nil
}
