// Code generated by trunnel. DO NOT EDIT.

package unions

import "testing"

func TestPacketCorpus(t *testing.T) {
	cases := []struct {
		Data []byte
	}{
		{
			Data: []byte{0x1, 0xf8},
		},
		{
			Data: []byte{0x2, 0xf9, 0xb4},
		},
		{
			Data: []byte{0x3, 0x6f, 0x63, 0x70, 0x0},
		},
	}
	for _, c := range cases {
		_, err := ParsePacket(c.Data)
		if err != nil {
			t.Fatal(err)
		}
	}
}
