// Code generated by trunnel. DO NOT EDIT.

//go:build gofuzz
// +build gofuzz

package unions

func FuzzPacket(data []byte) int {
	_, err := ParsePacket(data)
	if err != nil {
		return 0
	}
	return 1
}
