// Code generated by trunnel. DO NOT EDIT.

//go:build gofuzz
// +build gofuzz

package socks5

func FuzzSocks5ClientVersion(data []byte) int {
	_, err := ParseSocks5ClientVersion(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzSocks5ServerMethod(data []byte) int {
	_, err := ParseSocks5ServerMethod(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzDomainname(data []byte) int {
	_, err := ParseDomainname(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzSocks5ClientRequest(data []byte) int {
	_, err := ParseSocks5ClientRequest(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzSocks5ServerReply(data []byte) int {
	_, err := ParseSocks5ServerReply(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzSocks5ClientUserpassAuth(data []byte) int {
	_, err := ParseSocks5ClientUserpassAuth(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzSocks5ServerUserpathAuth(data []byte) int {
	_, err := ParseSocks5ServerUserpathAuth(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzSocks4ClientRequest(data []byte) int {
	_, err := ParseSocks4ClientRequest(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzSocks4ServerReply(data []byte) int {
	_, err := ParseSocks4ServerReply(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzTorSocksauthKeyval(data []byte) int {
	_, err := ParseTorSocksauthKeyval(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzTorExtendedSocksAuthRequest(data []byte) int {
	_, err := ParseTorExtendedSocksAuthRequest(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzTorExtendedSocksAuthResponse(data []byte) int {
	_, err := ParseTorExtendedSocksAuthResponse(data)
	if err != nil {
		return 0
	}
	return 1
}
