// Code generated by trunnel. DO NOT EDIT.

package strings

import "testing"

func TestMessageCorpus(t *testing.T) {
	cases := []struct {
		Data []byte
	}{
		{
			Data: []byte{0x94, 0x62, 0x79, 0x68, 0x69, 0x7a, 0x7a, 0x0, 0x1},
		},
	}
	for _, c := range cases {
		_, err := ParseMessage(c.Data)
		if err != nil {
			t.Fatal(err)
		}
	}
}
