// Code generated by trunnel. DO NOT EDIT.

//go:build gofuzz
// +build gofuzz

package strings

func FuzzMessage(data []byte) int {
	_, err := ParseMessage(data)
	if err != nil {
		return 0
	}
	return 1
}
