// Code generated by trunnel. DO NOT EDIT.

//go:build gofuzz
// +build gofuzz

package color

func FuzzColor(data []byte) int {
	_, err := ParseColor(data)
	if err != nil {
		return 0
	}
	return 1
}
