// Code generated by trunnel. DO NOT EDIT.

//go:build gofuzz
// +build gofuzz

package arrays

func FuzzSimpleArray(data []byte) int {
	_, err := ParseSimpleArray(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzFixedArray(data []byte) int {
	_, err := ParseFixedArray(data)
	if err != nil {
		return 0
	}
	return 1
}
