// Code generated by trunnel. DO NOT EDIT.

//go:build gofuzz
// +build gofuzz

package nested

func FuzzInner(data []byte) int {
	_, err := ParseInner(data)
	if err != nil {
		return 0
	}
	return 1
}

func FuzzOuter(data []byte) int {
	_, err := ParseOuter(data)
	if err != nil {
		return 0
	}
	return 1
}
